// ─── Jobs Controller ──────────────────────────────────────────────────────────
//
// Exposes the async job status polling API:
//
//   GET /api/v1/jobs/:id/status  — lightweight status check, fast
//   GET /api/v1/jobs/:id/result  — returns the full result when completed
//
// Design: these endpoints are unauthenticated by job ID alone, but the job ID
// is a UUID (128-bit entropy) generated by BullMQ — effectively unguessable.
// For Phase 7, bind job IDs to user IDs in the status record and validate ownership.

import type { Request, Response } from 'express';
import { asyncHandler } from '../utils/async-handler';
import { NotFoundError, ForbiddenError } from '../utils/errors';
import { jobTracker } from '../queue/job-tracker';

// ── GET /api/v1/jobs/:id/status ───────────────────────────────────────────────

export const getJobStatus = asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;

  const status = await jobTracker.getStatus(id);
  if (!status) {
    throw new NotFoundError(`Job ${id}`);
  }
  // Ownership check: jobs created after this deploy carry a userId; verify it matches.
  // Jobs created before (no userId in record) pass through — they expire within 24 h.
  if (status.userId && status.userId !== req.user!.userId) {
    throw new ForbiddenError();
  }

  // HTTP 202 = still processing, 200 = terminal state
  const httpStatus = ['waiting', 'active', 'delayed'].includes(status.status) ? 202 : 200;

  res.status(httpStatus).json({
    success: true,
    data: status,
  });
});

// ── GET /api/v1/jobs/:id/result ───────────────────────────────────────────────

export const getJobResult = asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;

  const status = await jobTracker.getStatus(id);
  if (!status) throw new NotFoundError(`Job ${id}`);
  if (status.userId && status.userId !== req.user!.userId) {
    throw new ForbiddenError();
  }

  if (status.status === 'failed') {
    res.status(422).json({
      success: false,
      error: 'Job failed',
      reason: status.failedReason ?? 'Unknown error',
      jobId: id,
    });
    return;
  }

  if (status.status !== 'completed') {
    res.status(202).json({
      success: false,
      error: 'Job not yet completed',
      status: status.status,
      progress: status.progress,
      message: status.message,
    });
    return;
  }

  const result = await jobTracker.getResult(id);
  if (!result) {
    // Result expired from Redis but job shows completed — client should use main API
    res.status(410).json({
      success: false,
      error: 'Result expired. Use the main API to retrieve the data.',
    });
    return;
  }

  res.json({ success: true, data: result });
});
